export const statsSAAreaCodeOptions = [
    // Western Cape
    { name: 'City of Cape Town', value: 'WC001' },
    { name: 'Matzikama', value: 'WC002' },
    { name: 'Cederberg', value: 'WC003' },
    { name: 'Bergrivier', value: 'WC004' },
    { name: 'Saldanha Bay', value: 'WC005' },
    { name: 'Swartland', value: 'WC006' },
    { name: 'Witzenberg', value: 'WC007' },
    { name: 'Drakenstein', value: 'WC008' },
    { name: 'Stellenbosch', value: 'WC009' },
    { name: 'Breede Valley', value: 'WC010' },
    { name: 'Langeberg', value: 'WC011' },
    { name: 'Theewaterskloof', value: 'WC031' },
    { name: 'Overstrand', value: 'WC032' },
    { name: 'Cape Agulhas', value: 'WC033' },
    { name: 'Swellendam', value: 'WC034' },
    { name: 'Kannaland', value: 'WC041' },
    { name: 'Hessequa', value: 'WC042' },
    { name: 'Mossel Bay', value: 'WC043' },
    { name: 'George', value: 'WC044' },
    { name: 'Oudtshoorn', value: 'WC045' },
    { name: 'Bitou', value: 'WC047' },
    { name: 'Knysna', value: 'WC048' },
    
    // Eastern Cape
    { name: 'Buffalo City', value: 'EC001' },
    { name: 'Nelson Mandela Bay', value: 'EC002' },
    { name: 'Amahlathi', value: 'EC103' },
    { name: 'Great Kei', value: 'EC104' },
    { name: 'Mbhashe', value: 'EC105' },
    { name: 'Mnquma', value: 'EC122' },
    { name: 'Mbizana', value: 'EC443' },
    { name: 'Ngqushwa', value: 'EC107' },
    { name: 'Nkonkobe', value: 'EC108' },
    { name: 'Nxuba', value: 'EC129' },
    { name: 'Inxuba Yethemba', value: 'EC131' },
    { name: 'Tsolwana', value: 'EC132' },
    { name: 'Inkwanca', value: 'EC133' },
    { name: 'Lukhanji', value: 'EC134' },
    { name: 'Intsika Yethu', value: 'EC135' },
    { name: 'Engcobo', value: 'EC137' },
    { name: 'Sakhisizwe', value: 'EC138' },
    { name: 'Elundini', value: 'EC141' },
    { name: 'Senqu', value: 'EC142' },
    { name: 'Maletswai', value: 'EC144' },
    { name: 'Gariep', value: 'EC145' },
    
    // Northern Cape
    { name: 'Sol Plaatje', value: 'NC091' },
    { name: 'Dikgatlong', value: 'NC092' },
    { name: 'Magareng', value: 'NC093' },
    { name: 'Phokwane', value: 'NC094' },
    { name: 'Joe Morolong', value: 'NC451' },
    { name: 'Ga-Segonyana', value: 'NC452' },
    { name: 'Gamagara', value: 'NC453' },
    { name: 'Kgatelopele', value: 'NC451' },
    { name: 'Tsantsabane', value: 'NC452' },
    { name: 'Khai-Ma', value: 'NC064' },
    { name: 'Hantam', value: 'NC065' },
    { name: 'Karoo Hoogland', value: 'NC066' },
    { name: 'Kamiesberg', value: 'NC074' },
    { name: 'Richtersveld', value: 'NC082' },
    { name: 'Nama Khoi', value: 'NC083' },
    { name: 'Karoo Hoogland', value: 'NC084' },
    
    // Free State
    { name: 'Masilonyana', value: 'FS161' },
    { name: 'Tokologo', value: 'FS162' },
    { name: 'Tswelopele', value: 'FS163' },
    { name: 'Matjhabeng', value: 'FS184' },
    { name: 'Nala', value: 'FS185' },
    { name: 'Mangaung', value: 'FS181' },
    { name: 'Kopanong', value: 'FS184' },
    { name: 'Letsemeng', value: 'FS185' },
    { name: 'Mohokare', value: 'FS163' },
    { name: 'Naledi', value: 'FS164' },
    { name: 'Setsoto', value: 'FS191' },
    { name: 'Dihlabeng', value: 'FS192' },
    { name: 'Nketoana', value: 'FS193' },
    { name: 'Maluti a Phofung', value: 'FS194' },
    { name: 'Phumelela', value: 'FS195' },
    
    // KwaZulu-Natal
    { name: 'eThekwini', value: 'KZN001' },
    { name: 'Mandeni', value: 'KZN211' },
    { name: 'KwaDukuza', value: 'KZN212' },
    { name: 'Ndwedwe', value: 'KZN213' },
    { name: 'Maphumulo', value: 'KZN214' },
    { name: 'uMhlathuze', value: 'KZN221' },
    { name: 'uMlalazi', value: 'KZN241' },
    { name: 'Ntambanana', value: 'KZN242' },
    { name: 'Mthonjaneni', value: 'KZN242' },
    { name: 'Nkandla', value: 'KZN244' },
    { name: 'Endumeni', value: 'KZN253' },
    { name: 'Nquthu', value: 'KZN254' },
    { name: 'Msinga', value: 'KZN255' },
    { name: 'Umvoti', value: 'KZN256' },
    { name: 'Umuziwabantu', value: 'KZN215' },
    
    // North West
    { name: 'Moretele', value: 'NW371' },
    { name: 'Madibeng', value: 'NW372' },
    { name: 'Rustenburg', value: 'NW373' },
    { name: 'Kgetlengrivier', value: 'NW374' },
    { name: 'Moses Kotane', value: 'NW375' },
    { name: 'Ratlou', value: 'NW381' },
    { name: 'Tswaing', value: 'NW382' },
    { name: 'Ditsobotla', value: 'NW384' },
    { name: 'Ramotshere Moiloa', value: 'NW385' },
    { name: 'Mafikeng', value: 'NW383' },
    { name: 'Naledi', value: 'NW392' },
    { name: 'Mamusa', value: 'NW393' },
    { name: 'Greater Taung', value: 'NW394' },
    
    // Gauteng
    { name: 'City of Tshwane', value: 'GT481' },
    { name: 'Ekurhuleni', value: 'GT484' },
    { name: 'City of Johannesburg', value: 'GT485' },
    { name: 'Lesedi', value: 'GT421' },
    { name: 'Emfuleni', value: 'GT422' },
    { name: 'Midvaal', value: 'GT423' },
    { name: 'Mogale City', value: 'GT481' },
    { name: 'Rand West City', value: 'GT482' },
    { name: 'Merafong City', value: 'GT483' },
    
    // Mpumalanga
    { name: 'Albert Luthuli', value: 'MP301' },
    { name: 'Msukaligwa', value: 'MP302' },
    { name: 'Mkhondo', value: 'MP303' },
    { name: 'Pixley Ka Seme', value: 'MP304' },
    { name: 'Lekwa', value: 'MP305' },
    { name: 'Govan Mbeki', value: 'MP307' },
    { name: 'Dipaleseng', value: 'MP308' },
    { name: 'Victor Khanye', value: 'MP309' },
    { name: 'Emalahleni', value: 'MP311' },
    { name: 'Steve Tshwete', value: 'MP312' },
    { name: 'Thembisile Hani', value: 'MP313' },
    { name: 'Dr JS Moroka', value: 'MP314' },
    { name: 'Bushbuckridge', value: 'MP315' },
    { name: 'Nkomazi', value: 'MP316' },
    { name: 'Thaba Chweu', value: 'MP317' },
    { name: 'Umjindi', value: 'MP321' },
    
    // Limpopo
    { name: 'Musina', value: 'LIM341' },
    { name: 'Thulamela', value: 'LIM342' },
    { name: 'Makhado', value: 'LIM343' },
    { name: 'Collins Chabane', value: 'LIM344' },
    { name: 'Blouberg', value: 'LIM351' },
    { name: 'Molemole', value: 'LIM353' },
    { name: 'Polokwane', value: 'LIM354' },
    { name: 'Lepele-Nkumpi', value: 'LIM355' },
    { name: 'Thabazimbi', value: 'LIM361' },
    { name: 'Lephalale', value: 'LIM362' },
    { name: 'Modimolle-Mookgophong', value: 'LIM364' },
    { name: 'Mogalakwena', value: 'LIM365' },
    { name: 'Bela-Bela', value: 'LIM366' },
    { name: 'Elias Motsoaledi', value: 'LIM471' },
    { name: 'Fetakgomo Tubatse', value: 'LIM472' },
    { name: 'Makhuduthamaga', value: 'LIM473' },
    { name: 'Ephraim Mogale', value: 'LIM474' },
    { name: 'Greater Letaba', value: 'LIM475' },
    { name: 'Maruleng', value: 'LIM476' },
    { name: 'Ba-Phalaborwa', value: 'LIM477' },
  ];
  